/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * An error occurred interacting with the API.
 */
export class APIError extends Error {
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "details" })
    details?: Record<string, any>;

    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message: string;

    constructor(err?: APIError) {
        super();
        if (err) {
            Object.assign(this, err);
        }

        this.name = "APIError";
        Object.setPrototypeOf(this, APIError.prototype);
    }
}
